### ISSUE TITLE
Unable to install in Windows

### ISSUE THREAD

**Issue by aromanowski** [HajkD/orthologr#1]
Dear HajkD,
I tried to install orthologr in a Win 8 laptop, running R Studio 0.98.1091 + R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet", Platform: x86_64-w64-mingw32/x64 (64-bit), and Bioconductor version 3.0 (BiocInstaller 1.16.5).

When I tried to install orthologr, I got the following message:

> devtools::install_github("HajkD/orthologr", build_vignettes = TRUE, dependencies = TRUE)
Downloading github repo HajkD/orthologr@master
Installing orthologr
Skipping 2 packages not available: Biostrings, IRanges
"C:/PROGRA~1/R/R-31~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  "C:/Users/Andres/AppData/Local/Temp/RtmpyKKyw9/devtools1620ecb385b/HajkD-orthologr-0c8658a"  \
  --library="d:/Users/Andres/Documents/R/win-library/3.1" --install-tests 

>* installing *source* package 'orthologr' ...
>** libs

>*** arch - i386
>Warning: running command 'make -f "C:/PROGRA~1/R/R-31~1.2/etc/i386/Makeconf" -f >"C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' >SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="orthologr.dll" OBJECTS="RcppExports.o gestimator.o"' had >status 127
>ERROR: compilation failed for package 'orthologr'
>* removing 'd:/Users/Andres/Documents/R/win-library/3.1/orthologr'
>Error: Command failed (1)

Could you help me?

Thank you very much in advance,
Andres

**Comment by aromanowski** [comment]
I found out how to work it out... maybe you can add it to the readme file =)

Here is how I solved this problem on my Windows 8 computer:

>Install Rtools
>Locate the folder that Rtools is installed. In my case it is at C:\Rtools.
>Add C:\Rtools\bin path to the system path.
>Adding C:\Rtools\bin to the system path:

>Go to Control Panel >> System and Security >> System
>Go to Advanced System Settings
>Open Advanced tab
>Click Environmental Variables... button
>Select Path variable and click Edit button
>If there is nothing as a "Variable Value" you can simply write C:\Rtools\bin. If there is already a >value, then add ;C:\Rtools\bin to the end of it.
>Click OK, OK...
>Restart R, it should work.

Hope this helps other Windows users that are interested in your R package!

Best,
Andres

**Comment by HajkD** [comment]
Dear Andres,

thank you very much! That's great! 

I added a troubleshooting section to the README.

Best,
Hajk
