### ISSUE TITLE
File input issue

### ISSUE THREAD

**Issue by HirokiTomida** [HajkD/orthologr#10]
Hello Dr. HajkD. 
I am amazed at your program! Thank you so much for sharing your work!

I am an college student and totally new to bioinfomatics So I may commit mistakes during my command. 
But I can not run your command properly even in your sample commands. (homo sapiens one)

I want to calculate genome wide dn/ds between two fish strains. 

I took my fasta.files from ensemble. HNI strain from[https://asia.ensembl.org/Oryzias_latipes_hni/Info/Index](url)
and HdrR strain from [https://asia.ensembl.org/Oryzias_latipes/Info/Index](url)

And this is my command.(almost copied your sample command)

> >`library(biomartr)
> dNdS(query_file      = system.file('Oryzias_latipes.ASM223467v1.cds.all.fa', package = 'orthologr'),
+      subject_file    = system.file('Oryzias_latipes_hni.ASM223471v1.cds.all.fa', package = 'orthologr'),
+      delete_corrupt_cds = TRUE, 
+      ortho_detection = "RBH",
+      aa_aln_type     = "pairwise", 
+      aa_aln_tool     = "NW",
+      codon_aln_tool  = "pal2nal",
+      dnds_est.method = "Comeron",
+      comp_cores      = 1 )
 value[[3L]](cond) でエラー: File  could not be read properly.
Please make sure that  contains only CDS sequences and is in fasta format.

This error message happen in your all sample commands on orthologr. So I wonder what is the problem.

I am using R3.5.1 version.  my OS is windows 10

I would appreciate very much if you enlighten me on this problem.

**Comment by HajkD** [comment]
Hi @HirokiTomida,

Many thanks for contacting me and I am happy that you find `orthologr` useful.

Could you please try to specify the argument `query_file = 'Oryzias_latipes.ASM223467v1.cds.all.fa'`  and `subject_file = 'Oryzias_latipes_hni.ASM223471v1.cds.all.fa'` rather than using `system.file(..., package = 'orthologr')`? This should do the trick.

The command `system.file(..., package = 'orthologr')` only refers to the example sequences stored in the `orthologr` package. Your real sequence files should be specified as a normal path.

Please let me know if this helps.

Best wishes,
Hajk

**Comment by HirokiTomida** [comment]
Hi @HajkD

Thank you so much for your kind advice.
I tried to fix my codes. But it seems not working. Can you point out.
I already checked my fa files However, it seems like fasta files. so I am not sure that is wrong this my codes.
May I ask you what can be the reasons of this error?

```
> result1<-dNdS(query_file = 'Oryzias_latipes.ASM223467v1.cds.all.fa',
+      subject_file = 'Oryzias_latipes_hni.ASM223471v1.cds.all.fa',
+      delete_corrupt_cds = TRUE, 
+      ortho_detection = "RBH",
+      aa_aln_type     = "pairwise", 
+      aa_aln_tool     = "NW",
+      codon_aln_tool  = "pal2nal",
+      dnds_est.method = "Comeron",
+      comp_cores      = 1 )
```
 
> value[[3L]](cond) 
>   File Oryzias_latipes.ASM223467v1.cds.all.fa could not be read properly.
> Please make sure that Oryzias_latipes.ASM223467v1.cds.all.fa contains only CDS sequences and is in fasta format.

Sincerely
Hiroki Tomida

**Comment by HajkD** [comment]
Hi @HirokiTomida,

That is strange. I just ran the following commands and was able to
generate a dNdS map.

I used my other package [biomartr](https://github.com/ropensci/biomartr) to retrieve the genomes you are interested in:

```r
# install.packages("biomartr")
olatipes_cds <- biomartr::getCDS(db = "ensembl", organism = "Oryzias latipes")
olatipes_hni_cds <- biomartr::getCDS(db = "ensembl", organism = "Oryzias latipes hni")
```

Ran the `dNdS()` function as following:

```r
result1 <- orthologr::dNdS(
                 query_file = olatipes_cds,
                 subject_file = olatipes_hni_cds,
                 delete_corrupt_cds = TRUE, 
                 ortho_detection = "RBH",
                 aa_aln_type     = "pairwise", 
                 aa_aln_tool     = "NW",
                 codon_aln_tool  = "pal2nal",
                 dnds_est.method = "Comeron",
                 comp_cores      = 28)
```

Retrieved the following output:

```
# A tibble: 782,670 x 15
   query_id      subject_id         dN      dS   dNdS perc_identity alig_length
   <chr>         <chr>           <dbl>   <dbl>  <dbl>         <dbl>       <dbl>
 1 ENSORLT00000… ENSORLT00020… 0.00816 0.00352 2.32            98.3        289.
 2 ENSORLT00000… ENSORLT00020… 0.00315 0.0237  0.133           98.6        489.
 3 ENSORLT00000… ENSORLT00020… 0.00244 0.0455  0.0535          99.4        175.
 4 ENSORLT00000… ENSORLT00020… 0.0116  0.0341  0.339           97.3        671.
 5 ENSORLT00000… ENSORLT00020… 0.0193  0.0554  0.349           98.5        266.
 6 ENSORLT00000… ENSORLT00020… 0.00251 0.0204  0.123           98.6        362.
 7 ENSORLT00000… ENSORLT00020… 0.00251 0.0204  0.123           95.5        359.
 8 ENSORLT00000… ENSORLT00020… 0.0276  0.0501  0.551           98.6        362.
 9 ENSORLT00000… ENSORLT00020… 0.0276  0.0501  0.551           95.5        359.
10 ENSORLT00000… ENSORLT00020… 0.00930 0.0365  0.255           98.0        405.
# ... with 782,660 more rows, and 8 more variables: mismatches <dbl>,
#   gap_openings <dbl>, q_start <dbl>, q_end <dbl>, s_start <dbl>, s_end <dbl>,
#   evalue <dbl>, bit_score <dbl>
```

And saved the results locally in a file named `olatipes_vs_olatipes_hni_dnds.csv` (see attachment [olatipes_vs_olatipes_hni_dnds.csv.zip](https://github.com/HajkD/orthologr/files/2563379/olatipes_vs_olatipes_hni_dnds.csv.zip)).

```r
utils::write.table(
                        result1,
                        "olatipes_vs_olatipes_hni_dnds.csv",
                        sep       = ";",
                        col.names = TRUE,
                        row.names = FALSE,
                        quote     = FALSE
                )
```

Be aware that the dNdS table contains dN, dS, dNdS, etc values for each individual transcript. So
when you want only gene loci you need to still filter them.

Before running `orthologr`, did you install all prerequisite tools as described here: https://hajkd.github.io/orthologr/articles/Install.html ?

I hope this helps?

Best wishes,
Hajk

**Comment by HirokiTomida** [comment]
@HajkD 
Thank you so much for kind comment and advice.
I noticed that I haven't installed C++11 yet. That may be why I could not run the command. Please accept my sincere apologies for the troubles caused by my lack of care.
I feel really sorry for bothering you. Thank you so much for helped me.

Sincerely
Hiroki Tomida
