### ISSUE TITLE
Error in ability to compile

### ISSUE THREAD

**Issue by DanielleMStevens** [HajkD/orthologr#11]
Hi,

Thank you so much in advance. I was hoping to use this packge for my work, but I am having some trouble trying to compile it. 
In terms of specs, I am working on a Windows computer with R 3.5.2 in R studio. 

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("Biostrings", version = "3.8")
install.packages("rtools")
install.packages("devtools")
install.packages("pkgbuild")
library(pkgbuild)
find_rtools(debug = TRUE)
devtools::install_github("HajkD/orthologr", build_vignettes = TRUE, dependencies = TRUE)

Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/DANIEL~1.STE/AppData/Local/Temp/RtmpW6Olzn/file301f4228420e9/orthologr_0.2.0.9000.tar.gz’ had non-zero exit status

I know Windows machines have problems and tried to correct for this by setting the path of my Rtools in the system settings. But this didn't seem to help. I think there seems to be some problem in the compilation of the binaries, but I'm new so I may have missed something. 

Thanks again!
Dani

**Comment by HajkD** [comment]
Hi Dani,

I am very sorry for replying so late. 
Many thanks for reaching out to me and I am very happy that you find `orthologr`
useful.

Did you have a chance to look at [this discussion](https://github.com/HajkD/orthologr/issues/1)?

If yes and it still doesn't work then I have to start troubleshooting.

I hope this helps.

Kind wishes,
Hajk
