### ISSUE TITLE
Problem calling `multi_aln` on windows

### ISSUE THREAD

**Issue by missuse** [HajkD/orthologr#12]
Hi,

First of all I'd like to thank you for the effort you put in this package.

I am trying to setup `orthologr` and one of the issues is with `multi_aln` function. When I try to run a simple call like:

```
res <- multi_aln(file = system.file('seqs/aa_seqs.fasta', package = 'orthologr'),
                 tool = "clustalw", 
                 get_aln = TRUE)
```

I get an error

`Error: It seems like you don't have ClustalW installed locally on your machine or the PATH variable to the ClustalW program is not set correctly.`

however `clustalw2.exe` is in my PATH and 

`system("clustalw2 -help")`

returns what it should. 

I have checked the source for `multi_aln` and I trust the offending part is the internal function

`orthologr:::is_installed_clustalw`

since it checks

`system("clustalw -help", intern = TRUE)`

regardless of operating system.

I think a simple solution would be to change this line to

`system(paste0(call_clustalw, " -help"))`

Thanks.

EDIT: Suggestion. Perhaps it would be more user friendly to add the package `msa`: https://bioconductor.org/packages/release/bioc/html/msa.html as a dependency to your package and remove some external dependencies

**Comment by HajkD** [comment]
Hi Milan,

Many thanks for reaching out to me and for notifying me about this bug.
I very much appreciate your help!

I fixed this issue and you should now be able to run the `multi_aln()` function with `ClustalW2`.

Thank you so much for pointing the `msa` package out to me. I will have a look at it and added it to my `orthologr` TODO list to incorporate the `msa` package into `orthologr`. I like a lot that all tools are already part of the package and don't need to be installed. 

In any case, I am also working on a `conda recipe` and `conda install` procedure for orthologr which should make the installation of dependencies more straight forward.

I hope this helps!

Many thanks and best wishes,
Hajk

**Comment by missuse** [comment]
Hi Hajk-Georg,

Thank you for the prompt response and fix. The issue was resolved!

Every call to the function returns the warning:
```
Warning message:
In system(paste0(call_clustalw, " -help"), intern = TRUE) :
  running command 'clustalw2.exe -help' had status 1
```

but the command executes without issues.

Kind regards,

Milan

**Comment by HajkD** [comment]
Hi Milan,

Brilliant. I also added a `suppressWarnings()` so that this warning doesn't appear anymore. The warning is caused by the interactive nature of the `clustalw` command line interface. 

I am happy that it works now!

Cheers,
Hajk
