### ISSUE TITLE
Problem calling `blast` on windows

### ISSUE THREAD

**Issue by missuse** [HajkD/orthologr#13]
Hi again,

Another issue I am experiencing is with the `blast` function on Windows 10. When I try to run a simple call like:

```
res <- blast(query_file = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
             subject_file = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'),
             save.output = getwd())
```

I get the following error:

```
Error: Too many positional arguments (1), the offending value: qseqid
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: qseqid
Error in value[[3L]](cond) : 
  File blastresult_ortho_thal_cds.fasta.csv could not be read correctly. Please check the correct path to blastresult_ortho_thal_cds.fasta.csv or whether BLAST did write the resulting hit table correctly.
```

Blast is in my PATH and 

`system("blastp -help")`

returns what it should

I trust this is related to: https://stackoverflow.com/questions/20086291/blastdbcmd-too-many-positional-arguments-1-the-offending-value-f and http://www.metagenomics.wiki/tools/blast/error-too-many-positional-arguments

I could not find the offending `-` in the source code. 

Thanks

**Comment by HajkD** [comment]
Hi Milan,

Many thanks for also pointing this one out to me.

Could you please let me know which BLAST version you are using for me to trouble shoot?
Or could you maybe provide a small example case in which this error occurs? 

Your help with this is truly appreciated. 

Btw: Thanks for mentioning the `rBLAST` package, but I am working on a project myself called [metablastr](https://github.com/HajkD/metablastr) which in the long term will also be the core of `orthologr`.

Many thanks and best wishes,
Hajk

**Comment by missuse** [comment]
Hi,

I am using `Protein-Protein BLAST 2.7.1+`

The issue can be reproduced with

```
res <- blast(query_file = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
             subject_file = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'))
```

the output is:

`Running blastp: 2.7.1+ ...


Building a new DB, current time: 07/05/2019 16:25:36
New DB name:   C:\Users\missu\AppData\Local\Temp\RtmpsZ7STc\_blast_db\blastdb_ortho_lyra_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_lyra_cds.fasta_protein.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.0024322 seconds.
USAGE
  blastp [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-entrez_query entrez_query] [-db_soft_mask filtering_algorithm]
    [-db_hard_mask filtering_algorithm] [-subject subject_input_file]
    [-subject_loc range] [-query input_file] [-out output_file]
    [-evalue evalue] [-word_size int_value] [-gapopen open_penalty]
    [-gapextend extend_penalty] [-qcov_hsp_perc float_value]
    [-max_hsps int_value] [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value]
    [-sum_stats bool_value] [-seg SEG_options] [-soft_masking soft_masking]
    [-matrix matrix_name] [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-window_size int_value] [-lcase_masking] [-query_loc range]
    [-parse_deflines] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-ungapped] [-remote] [-comp_based_stats compo]
    [-use_sw_tback] [-version]

DESCRIPTION
   Protein-Protein BLAST 2.7.1+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value: qseqid
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: qseqid
Error in value[[3L]](cond) : 
  File blastresult_ortho_thal_cds.fasta.csv could not be read correctly. Please check the correct path to blastresult_ortho_thal_cds.fasta.csv or whether BLAST did write the resulting hit table correctly.`

I have also tried updating to the latest blast. The print out is:

```
Running blastp: 2.9.0+ ...


Building a new DB, current time: 07/05/2019 16:29:24
New DB name:   C:\Users\missu\AppData\Local\Temp\RtmpY3xCNc\_blast_db\blastdb_ortho_lyra_cds.fasta_protein.fasta
New DB title:  blastdb_ortho_lyra_cds.fasta_protein.fasta
Sequence type: Protein
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 20 sequences in 0.0026546 seconds.
USAGE
  blastp [-h] [-help] [-import_search_strategy filename]
    [-export_search_strategy filename] [-task task_name] [-db database_name]
    [-dbsize num_letters] [-gilist filename] [-seqidlist filename]
    [-negative_gilist filename] [-negative_seqidlist filename]
    [-taxids taxids] [-negative_taxids taxids] [-taxidlist filename]
    [-negative_taxidlist filename] [-ipglist filename]
    [-negative_ipglist filename] [-entrez_query entrez_query]
    [-db_soft_mask filtering_algorithm] [-db_hard_mask filtering_algorithm]
    [-subject subject_input_file] [-subject_loc range] [-query input_file]
    [-out output_file] [-evalue evalue] [-word_size int_value]
    [-gapopen open_penalty] [-gapextend extend_penalty]
    [-qcov_hsp_perc float_value] [-max_hsps int_value]
    [-xdrop_ungap float_value] [-xdrop_gap float_value]
    [-xdrop_gap_final float_value] [-searchsp int_value] [-seg SEG_options]
    [-soft_masking soft_masking] [-matrix matrix_name]
    [-threshold float_value] [-culling_limit int_value]
    [-best_hit_overhang float_value] [-best_hit_score_edge float_value]
    [-subject_besthit] [-window_size int_value] [-lcase_masking]
    [-query_loc range] [-parse_deflines] [-outfmt format] [-show_gis]
    [-num_descriptions int_value] [-num_alignments int_value]
    [-line_length line_length] [-html] [-sorthits sort_hits]
    [-sorthsps sort_hsps] [-max_target_seqs num_sequences]
    [-num_threads int_value] [-ungapped] [-remote] [-comp_based_stats compo]
    [-use_sw_tback] [-version]

DESCRIPTION
   Protein-Protein BLAST 2.9.0+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: qseqid
Error in value[[3L]](cond) : 
  File blastresult_ortho_thal_cds.fasta.csv could not be read correctly. Please check the correct path to blastresult_ortho_thal_cds.fasta.csv or whether BLAST did write the resulting hit table correctly.
```
I should add that I can use blast from cmd.

After I posted the EDIT about `rBLAST` I saw you are working on `metablastr` so I deleted that part. 

I will try running the `metablastr` command and see if it works.

Thank you,

Milan

**Comment by HajkD** [comment]
Hi Milan,

Many thanks for this detailed response. I will look into this and will come back to you when I found a solution.

Cheers,
Hajk

**Comment by missuse** [comment]
Hi Hajk,

I just wanted to give you an update.
I tried running the same call using `rBLAST`, It works without issue:

```
library(rBLAST)
file.copy(system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'),
          'ortho_lyra_cds.fasta')
makeblastdb('ortho_lyra_cds.fasta', dbtype = "nucl")
bl <- blast(db= "ortho_lyra_cds.fasta", type = "blastn")
query_seq <- readDNAStringSet(system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'))
cl <- predict(bl, query_seq)
```
Perhaps comparison of the functions from rBLAST and orthologr can pinpoint the issue. When I have more time I will try to find the offending part.

All the best,

Milan

**Comment by HajkD** [comment]
Hi Milan,

That's brilliant! Thank you so much. I will have a look now as well and I very much appreciate your help with this.

Cheers,
Hajk

**Comment by missuse** [comment]
Hi Hajk,

I found the problem, it is in the line:

```
system(paste0("blastp -db ", database, " -query ", 
                    input, " -evalue ", eval, " -max_target_seqs ", 
                    max.target.seqs, " -out ", output, " -num_threads ", 
                    comp_cores, " -outfmt '6", " qseqid sseqid pident nident length mismatch gapopen gaps positive ppos qstart qend qlen qcovs qcovhsp sstart send slen evalue bitscore score'"))
```

the single quite  '6 qseqid sseqid pident nident length mismatch gapopen gaps positive ppos qstart qend qlen qcovs qcovhsp sstart send slen evalue bitscore score' makes problems on my window machine.

When I reverse the quotes 

```
system(paste0('blastp -db ', database, ' -query ', 
              input, ' -evalue ', '1E-5', ' -max_target_seqs ', 
              max.target.seqs, ' -out ', output, ' -num_threads ', 
              '1', ' -outfmt "6', ' qseqid sseqid pident nident length mismatch gapopen gaps positive ppos qstart qend qlen qcovs qcovhsp sstart send slen evalue bitscore score"'))
```

the call executes without problems.

Kind regards,

Milan

**Comment by HajkD** [comment]
Hi Milan,

Absolutely brilliant! I fixed it now and would you mind checking if it works for you now?

Thank you so very much for taking the time to find the solution to this issue. 

Other Windows users will be very grateful to you :-)

I will now also add the same modification in the `metablastr` package and would be grateful if you could swiftly check if it works there as well.

Many many thanks!

Hajk

**Comment by missuse** [comment]
Hi Hajk,

I tried on two Windows 10 machines and they work great: `orthologr:::blast`  as well as `metablastr::blast_nucleotide_to_nucleotide`
Thanks a lot for the prompt fix, I appreciate it.

I will be playing a bit with both packages in the near future and I will be sure to report if I encounter any problems. For now I am a fan of biomartr.

All the best,

Milan

**Comment by HajkD** [comment]
Hi Milan,

It makes me very very happy that it works for you now and thank you very much for your kind words. 

I truly hope that I can manage to implement more useful tools and functions in the future and will be tremendously grateful for your feedback on this journey :-)

Let's keep up the brilliant work! It was fun working with you on this! Very efficient :-)

Many thanks and all the best,
Hajk
