### ISSUE TITLE
How can I output blast_rec() results to file?

### ISSUE THREAD

**Issue by paul-sheridan** [HajkD/orthologr#15]
Hi Hajk,

I ran your example command:

\# save the BLAST output file to the current working directory
blast_rec(query_file   = system.file('seqs/ortho_thal_aa.fasta', package = 'orthologr'),
          subject_file = system.file('seqs/ortho_lyra_aa.fasta', package = 'orthologr'),
          seq_type     = "protein",
          save.output  = getwd())

I found the output files blastresult_ortho_lyra_aa.fasta.csv and blastresult_ortho_thal_aa.fasta.csv in my working directory. But I'm unable to find a .csv file with the full results of the following output that is printed to the console:

\# A tibble: 20 x 21
\# Groups:   query_id [20]
   query_id subject_id perc_identity num_ident_match… alig_length mismatches gap_openings n_gaps
   <chr>    <chr>              <dbl>            <int>       <int>      <int>        <int>  <int>
 1 AT1G010… 333554|PA…          74.0              347         469         80            8     42
 2 AT1G010… 470181|PA…          91.1              224         246         22            0      0
 3 AT1G010… 470180|PA…          95.5              343         359         12            2      4
20 AT1G012… 470155|PA…          96.7             1021        1056         35            0      0
\# … with 13 more variables: pos_match <int>, ppos <dbl>, q_start <int>, q_end <int>, q_len <int>,
\#   qcov <dbl>, qcovhsp <dbl>, s_start <int>, s_end <int>, s_len <int>, evalue <dbl>,
\#   bit_score <dbl>, score_raw <dbl>

Note: I excised rows 4 to 19 for brevity.

How can I best access the full table of these results? For example, is there a way to output them to a .csv file?

Thanks in Advance,

Paul

**Comment by HajkD** [comment]
Hi Paul,

Many thanks for contacting me.

Does this solve it?

```r
res <- orthologr::blast_rec(query_file = system.file('seqs/ortho_thal_aa.fasta', package = 'orthologr'),
subject_file = system.file('seqs/ortho_lyra_aa.fasta', package = 'orthologr'),
seq_type = "protein",
save.output = getwd())

#install.packages("readr")
readr::write_csv(res, "output.csv", col_names = TRUE)
```


Let me know if this helps.

Cheers,
Hajk

**Comment by paul-sheridan** [comment]
Hi Hajk,

Yes, I do believe that gets me sorted out.

Thanks Again,

Paul
