### ISSUE TITLE
Can not download orthologr

### ISSUE THREAD

**Issue by YUZHAN2019** [HajkD/orthologr#16]
Dear Contributor,

      I am trying to download orthologr, but always have the the following errors. Could you take a look or give me some suggestions? thanks. I am using R 3.6 in Wiondows 7 enterprise.   yu

> devtools::install_github("HajkD/orthologr", build_vignettes = TRUE, dependencies = TRUE)
Downloading GitHub repo HajkD/orthologr@master
Skipping 4 packages not available: biomartr, Biostrings, IRanges, rtracklayer
Downloading GitHub repo HajkD/metablastr@master
Skipping 7 packages not available: Biostrings, GenomicFeatures, GenomicRanges, Rsamtools, biomartr, IRanges, rtracklayer
Skipping 2 packages ahead of CRAN: DBI, BH
Installing 20 packages: dplyr, doParallel, RPostgreSQL, GenomicFeatures, GenomicRanges, Rsamtools, scales, RSQLite, biomartr, ggridges, rtracklayer, rlang, bit64, blob, digest, plyr, vctrs, nlme, Matrix, bit
Error: Failed to install 'orthologr' from GitHub:
  Failed to install 'metablastr' from GitHub:
  (converted from warning) packages ‘GenomicFeatures’, ‘GenomicRanges’, ‘Rsamtools’, ‘biomartr’, ‘rtracklayer’ are not available (for R version 3.6.0)

**Comment by HajkD** [comment]
Hi @YUZHAN2019 

Many thanks for contacting me and making me aware of this issue.

Since `R` version `> 3.6` was released a lot of new features and updates are required that I might have missed.

I now updated some internal functions of `orthologr` and hope the problem is solved now.

Could you please try to follow the following procedures to install `orthologr`:

```r
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install()
# Install package dependencies
BiocManager::install(c("Biostrings", "GenomicRanges", "GenomicFeatures", "Rsamtools", "rtracklayer"))

# install orthologr from GitHub
devtools::install_github("HajkD/metablastr")

# install orthologr from GitHub
devtools::install_github("HajkD/orthologr")
```

Did this work for you?

Many thanks,
Hajk

**Comment by YUZHAN2019** [comment]
Hello Dr. Drost,

          Many thanks for your update.
          I just tried your code, most of them works very well except the last one. The install information is following, let me know any other information you need. thanks again.

 yu
12.21

> devtools::install_github("HajkD/orthologr")
Downloading GitHub repo HajkD/orthologr@master
Skipping 3 packages not available: Biostrings, IRanges, rtracklayer
Installing 1 packages: dtplyr
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/dtplyr_1.0.0.zip'
Content type 'application/zip' length 97041 bytes (94 KB)
downloaded 94 KB

package ‘dtplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\YUZHAN\AppData\Local\Temp\RtmpcpRDc3\downloaded_packages
✓  checking for file 'C:\Users\YUZHAN\AppData\Local\Temp\RtmpcpRDc3\remotes63685b6f7de1\HajkD-orthologr-c7c60ba/DESCRIPTION' (428ms)
─  preparing 'orthologr': (599ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (373ms)
─  checking for empty or unneeded directories
─  building 'orthologr_0.4.0.tar.gz'

* installing *source* package 'orthologr' ...
** using staged installation
** libs

*** arch - i386
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_32/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c gestimator.cpp -o gestimator.o
gestimator.cpp: In function 'void gestimator(std::string, std::string, int, bool, bool)':
gestimator.cpp:141:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < length; ++i)
                   ^
C:/RBuildTools/3.5/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O3 -Wall  -std=gnu99 -mtune=generic -c orthologr_init.c -o orthologr_init.o
C:/RBuildTools/3.5/mingw_32/bin/g++ -shared -s -static-libgcc -o orthologr.dll tmp.def RcppExports.o gestimator.o orthologr_init.o -LC:/PROGRA~1/R/R-36~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.6.0/library/00LOCK-orthologr/00new/orthologr/libs/i386

*** arch - x64
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c gestimator.cpp -o gestimator.o
gestimator.cpp: In function 'void gestimator(std::string, std::string, int, bool, bool)':
gestimator.cpp:141:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (i = 0; i < length; ++i)
                   ^
C:/RBuildTools/3.5/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-36~1.0/include" -DNDEBUG -I../src -DRCPP_DEFAULT_INCLUDE_CALL=false -DCOMPILING_ORTHOLOGR -DBOOST_NO_INT64_T -DBOOST_NO_INTEGRAL_INT64_T -DBOOST_NO_LONG_LONG -DRCPP_USING_UTF8_ERROR_STRING -DRCPP_USE_UNWIND_PROTECT  -I"C:/Program Files/R/R-3.6.0/library/Rcpp/include"        -O2 -Wall  -std=gnu99 -mtune=generic -c orthologr_init.c -o orthologr_init.o
C:/RBuildTools/3.5/mingw_64/bin/g++ -shared -s -static-libgcc -o orthologr.dll tmp.def RcppExports.o gestimator.o orthologr_init.o -LC:/PROGRA~1/R/R-36~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.6.0/library/00LOCK-orthologr/00new/orthologr/libs/x64
** R
** inst
** byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'data.table' was built under R version 3.6.1
Execution halted
ERROR: lazy loading failed for package 'orthologr'
* removing 'C:/Program Files/R/R-3.6.0/library/orthologr'
Error: Failed to install 'orthologr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/YUZHAN/AppData/Local/Temp/RtmpcpRDc3/file63684aae13c8/orthologr_0.4.0.tar.gz’ had non-zero exit status






YU ZHAN

Graduate student

Department of Biology

Saint Louis University

________________________________

**Comment by HajkD** [comment]
It seems like the `data.table` package cannot be installed.

Have you tried this?

https://stackoverflow.com/questions/32721775/problems-installing-data-table-for-r

Just install the `data.table` package separately and then install `orthologr`.

```r
install.packages("data.table")
devtools::install_github("HajkD/orthologr")
```

Did this work for you?

Many thanks,
Hajk

**Comment by enocancerz** [comment]
Uuu
