### ISSUE TITLE
Problem with input files in pal2nal

### ISSUE THREAD

**Issue by harojm** [HajkD/orthologr#5]
Hi, we ran the program as follows:
```
library(orthologr)
dNdS(query_file = "/home/rohit/mario/V_vulnificus/orthologr/test1_genesv2.fasta",
 subject_file = "/home/rohit/mario/V_vulnificus/orthologr/test2_genesv2.fasta",
 seq_type = "cds",
 format = "fasta",
 ortho_detection = "RBH",
 eval = "1E-5",
 aa_aln_type = "multiple",
 aa_aln_tool = "muscle",
 codon_aln_tool = "pal2nal",
 dnds_est.method = "YN",
 comp_cores = 30,
 quiet = FALSE,
 clean_folders = FALSE)
```

However, we found this message when the program tries to use pal2nal: "Can't open /tmp/RtmpFcPl9s/_alignment/multi_aln/q3922_muscle.aln at /home/rohit/josemanuel/programs/R-3.4.0/library/orthologr/pal2nal/pal2nal.v14/pal2nal.pl line 365." Searching on the temporal files, we've seen that the program is calling to all the alignment files as q3922_aa.fasta_q3922_muscle.aln, instead of naming them according to the previuous name (q3922_muscle.aln). We've manually changed the name of the file as it should be, and we've run again the program. After this modification, pal2nal recognises the files giving us at the end the folling file:

> "3893"	"VV2_1642"	"VVMO6_03409"	0.00492299	0.0714542	0.0688972	"YN"
> "3894"	"VV2_1643"	"VVMO6_03410"	0.012254	0.0422009	0.290372	"YN"
> "3895"	"VV2_1644"	"VVMO6_03411"	0.00118025	0.0344713	0.0342386	"YN"
> "3896"	"VV2_1645"	"VVMO6_03412"	NA	0.0383651	0	"YN"
> "3897"	"VV2_1646"	"VVMO6_03413"	0.000974747	0.0588005	0.0165772	"YN"
> "3898"	"VV2_1647"	"VVMO6_03414"	NA	0.0235932	0	"YN"
> "3899"	"VV2_1648"	"VVMO6_03415"	NA	0.0331962	0	"YN"
> "3900"	"VV2_1649"	"VVMO6_03416"	0.00118043	0.0173107	0.0681908	"YN"
> "3901"	"VV2_1650"	"VVMO6_03417"	0.00458339	0.0794807	0.0576667	"YN"
> "3902"	"VV2_1651"	"VVMO6_03418"	0.00266173	0.0492652	0.0540286	"YN"
> "3903"	"VV2_1652"	"VVMO6_03419"	0.00821594	0.098678	0.0832601	"YN"
> "3904"	"VV2_1653"	"VVMO6_03420"	NA	0.0265769	0	"YN"

Can you please give us a solution to this error, in order to run it in one single step.

Many thanks in advance.

**Comment by HajkD** [comment]
Dear @harojm,

Thank you so much for pointing this bug out to me!

I found the issue and fixed it.

The problem was a wrong internal path reference in the `multi_aln()` function.

```r
if (!is.null(multi_aln_name)) {
                file.out <-
                        file.path(
                                tempdir(),
                                "_alignment",
                                "multi_aln",
                                paste0(basename(file), "_", multi_aln_name, "_", tool, ".aln")
                        )
        }
```

Instead of `paste0(basename(file), "_", multi_aln_name, "_", tool, ".aln")` the correct
reference had to be `paste0(multi_aln_name, "_", tool, ".aln")` (without the `basename(file), "_", `).

I now fixed this issue and pushed a new version of `biomartr` to GitHub.

I ran the following command to test if everything is working:

```r
 dNdS(query_file = system.file('seqs/ortho_thal_cds.fasta', package = 'orthologr'),
 subject_file = system.file('seqs/ortho_lyra_cds.fasta', package = 'orthologr'),
 seq_type = "cds",
 format = "fasta",
 ortho_detection = "RBH",
 eval = "1E-5",
 aa_aln_type = "multiple",
 aa_aln_tool = "muscle",
 codon_aln_tool = "pal2nal",
 dnds_est.method = "YN",
 comp_cores = 1,
 quiet = FALSE,
 clean_folders = FALSE)
```

```
Mission accomplished.
Method(s): YN 
Genetic code: 1-Standard Code
Please wait while reading sequences and calculating...
1 AT1G01220.1-470155|PACid:16047984	[OK]
Mission accomplished. (Time elapsed: 0:0)
       query_id            subject_id         dN        dS      dNdS method
 1: AT1G01010.1 333554|PACid:16033839 0.10458500 0.2720970 0.3843690     YN
 2: AT1G01020.1 470181|PACid:16064328 0.04164150 0.0951677 0.4375590     YN
 3: AT1G01030.1 470180|PACid:16054974 0.01667570 0.1115800 0.1494520     YN
 4: AT1G01040.1 333551|PACid:16057793 0.01699700 0.1310630 0.1296860     YN
 5: AT1G01050.1 909874|PACid:16064489         NA 0.2092450 0.0000000     YN
 6: AT1G01060.3 470177|PACid:16043374 0.04381220 0.1085330 0.4036770     YN
 7: AT1G01070.1 918864|PACid:16052578 0.01914650 0.0938974 0.2039080     YN
 8: AT1G01080.1 909871|PACid:16053217 0.03930610 0.0995795 0.3947210     YN
 9: AT1G01090.1 470171|PACid:16052860 0.00992468 0.2496620 0.0397525     YN
10: AT1G01110.2 333544|PACid:16034284 0.03292970 0.1293160 0.2546450     YN
11: AT1G01120.1 918858|PACid:16049140 0.00356132 0.1225410 0.0290623     YN
12: AT1G01140.3 470161|PACid:16036015 0.00582238 0.1354990 0.0429699     YN
13: AT1G01150.1 918855|PACid:16037307 0.12939600 0.2050850 0.6309360     YN
14: AT1G01160.1 918854|PACid:16044153 0.10804100 0.2209000 0.4890950     YN
15: AT1G01170.2 311317|PACid:16052302 0.00564482 0.2580050 0.0218787     YN
16: AT1G01180.1 909860|PACid:16056125 0.03729360 0.1601690 0.2328390     YN
17: AT1G01190.1 311315|PACid:16059488 0.02884810 0.1482150 0.1946360     YN
18: AT1G01200.1 470156|PACid:16041002 0.01983450 0.1512510 0.1311360     YN
19: AT1G01210.1 311313|PACid:16057125 0.02106910 0.1433630 0.1469630     YN
20: AT1G01220.1 470155|PACid:16047984 0.01530070 0.1446480 0.1057780     YN
```

I hope that it works now for you now :-)

Please let me know if I can improve anything else.

Many thanks and best wishes,
Hajk

**Comment by harojm** [comment]
Dear @HajkD, 
thanks! now the program works nicely. 
We let you know if we have some future comments to improve your work.

Kind regards,
@harojm.
