### ISSUE TITLE
clustalw in multi_aln 

### ISSUE THREAD

**Issue by aehr2** [HajkD/orthologr#6]
Hi Hajk,

I installed clustalw with "conda install -c biobuilds clustalw" on my Linux system.

And the binary is called  "clustalw2". 

So I can not call multi_aln.

best,
Claus

**Comment by HajkD** [comment]
Hi Claus,

Many thanks for making me aware of this issue!

I will have a look at the issue and will come back to you soon.

Best wishes,
Hajk

**Comment by HajkD** [comment]
Hi Claus,

I just changed the system call for Linux from `clustalw` to `clustalw2`. 

Please let me know if it now worked for you?

Many thanks and best wishes,
Hajk
